[irc]
server = "ip/uri"
port = 123
use_tls = true
accept_invalid_certs = true
nickname = "ACU-BRIDGE"
channels = ["#test-irc-haha"]

[discord]
token = "UwU"

[[channels]]
irc = "#test-irc-haha"
discord = "1475796938766160025"
